import type { Metadata } from "next";
import { Kanit, Roboto, Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";
import { SectionProvider } from "@/contexts/sectionContext";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["200", "400", "600"]
})

const kanit = Kanit({
  variable: "--font-kanit",
  subsets: ["latin"],
  weight: '900'
})

export const metadata: Metadata = {
  title: "Hi, I'm Huy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${kanit.variable} antialiased bg-black`}
      >
        <SectionProvider>
          <Header/>
          {children}
        </SectionProvider>
      </body>
    </html>
  );
}
