import type { Metadata } from "next";
import { Kanit, Roboto, Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400","300","200"]
})

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["200", "400", "600"]
})

const kanit = Kanit({
  variable: "--font-kanit",
  subsets: ["latin"],
  weight: '900'
})

export const metadata: Metadata = {
  title: "Hi, I'm Huy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${kanit.variable} antialiased bg-black`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
